# Generated by Django 4.2 on 2026-02-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='action',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('CLOSE', 'Close'), ('CREATE', 'Create'), ('UPDATE', 'Update')], default='STATUS_CHANGE', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
