# Generated by Django 4.2 on 2026-02-20 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exceptions", "0002_remove_auditlog_action_auditlog_action_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExceptionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_assets", models.IntegerField()),
                ("short_description", models.TextField()),
                ("reason_for_exception", models.TextField()),
                ("compensatory_controls", models.TextField(blank=True)),
                ("risk_score", models.IntegerField(blank=True, null=True)),
                ("risk_rating", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_deadline",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Deadline for approval (created_at + exception_type.approval_sla_days)",
                        null=True,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the exception was approved",
                        null=True,
                    ),
                ),
                (
                    "exception_end_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When the approved exception validity expires",
                        null=True,
                    ),
                ),
                (
                    "last_reminder_sent",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time a reminder was sent to approver",
                        null=True,
                    ),
                ),
                (
                    "reminder_stage",
                    models.CharField(
                        choices=[
                            ("None", "No reminder sent"),
                            ("Reminder_50", "50% of approval window"),
                            ("Reminder_75", "75% of approval window"),
                            ("Reminder_90", "90% of approval window"),
                            ("Expired_Notice", "Expired notification sent"),
                        ],
                        default="None",
                        help_text="Track which reminder stage has been sent",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft - Not Yet Submitted"),
                            ("Submitted", "Submitted - Pending Approval"),
                            ("Approved", "Approved - Active Exception"),
                            ("Rejected", "Rejected - Awaiting Resubmission"),
                            ("Expired", "Expired - Approval Deadline Passed"),
                            ("Closed", "Closed - Exception No Longer Valid"),
                        ],
                        db_index=True,
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("version", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Exception Request",
                "verbose_name_plural": "Exception Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("in_app", "In-App Notification"),
                            ("system", "System Log"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("None", "No reminder sent"),
                            ("Reminder_50", "50% of approval window"),
                            ("Reminder_75", "75% of approval window"),
                            ("Reminder_90", "90% of approval window"),
                            ("Expired_Notice", "Expired notification sent"),
                        ],
                        max_length=50,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("message_content", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.RemoveField(
            model_name="exception",
            name="asset_purpose",
        ),
        migrations.RemoveField(
            model_name="exception",
            name="asset_type",
        ),
        migrations.RemoveField(
            model_name="exception",
            name="business_unit",
        ),
        migrations.RemoveField(
            model_name="exception",
            name="data_classification",
        ),
        migrations.RemoveField(
            model_name="exception",
            name="data_components",
        ),
        migrations.RemoveField(
            model_name="exception",
            name="exception_type",
        ),
        migrations.RemoveField(
            model_name="exception",
            name="internet_exposure",
        ),
        migrations.RemoveField(
            model_name="exception",
            name="requestor",
        ),
        migrations.RemoveField(
            model_name="exception",
            name="risk_issue",
        ),
        migrations.RemoveField(
            model_name="exception",
            name="risk_owner",
        ),
        migrations.AlterModelOptions(
            name="assetpurpose",
            options={"ordering": ["name"], "verbose_name_plural": "Asset Purposes"},
        ),
        migrations.AlterModelOptions(
            name="assettype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="businessunit",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="dataclassification",
            options={"ordering": ["weight"]},
        ),
        migrations.AlterModelOptions(
            name="datacomponent",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="exceptiontype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="internetexposure",
            options={
                "ordering": ["weight"],
                "verbose_name_plural": "Internet Exposures",
            },
        ),
        migrations.AlterModelOptions(
            name="riskissue",
            options={"ordering": ["title"], "verbose_name_plural": "Risk Issues"},
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="exception",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="exceptiontype",
            name="approval_sla_days",
            field=models.IntegerField(
                default=28, help_text="Days allowed for approval before escalation"
            ),
        ),
        migrations.AlterField(
            model_name="assetpurpose",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="assettype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("SUBMIT", "Submitted for Approval"),
                    ("APPROVE", "Approved"),
                    ("REJECT", "Rejected"),
                    ("CLOSE", "Closed"),
                    ("EXPIRE", "Expired"),
                    ("REMIND", "Reminder Sent"),
                    ("ESCALATE", "Escalated"),
                    ("UPDATE", "Updated"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="businessunit",
            name="cio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="businessunit",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="dataclassification",
            name="level",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="datacomponent",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="exceptiontype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="internetexposure",
            name="label",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="riskissue",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name="Exception",
        ),
        migrations.AddField(
            model_name="reminderlog",
            name="exception_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reminder_logs",
                to="exceptions.exceptionrequest",
            ),
        ),
        migrations.AddField(
            model_name="reminderlog",
            name="sent_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exceptionrequest",
            name="asset_purpose",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="exceptions.assetpurpose",
            ),
        ),
        migrations.AddField(
            model_name="exceptionrequest",
            name="asset_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="exceptions.assettype"
            ),
        ),
        migrations.AddField(
            model_name="exceptionrequest",
            name="assigned_approver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approvals_pending",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exceptionrequest",
            name="assigned_risk_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="risk_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exceptionrequest",
            name="business_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="exceptions.businessunit",
            ),
        ),
        migrations.AddField(
            model_name="exceptionrequest",
            name="data_classification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="exceptions.dataclassification",
            ),
        ),
        migrations.AddField(
            model_name="exceptionrequest",
            name="data_components",
            field=models.ManyToManyField(to="exceptions.datacomponent"),
        ),
        migrations.AddField(
            model_name="exceptionrequest",
            name="exception_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="exceptions.exceptiontype",
            ),
        ),
        migrations.AddField(
            model_name="exceptionrequest",
            name="internet_exposure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="exceptions.internetexposure",
            ),
        ),
        migrations.AddField(
            model_name="exceptionrequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requested_exceptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exceptionrequest",
            name="risk_issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="exceptions.riskissue"
            ),
        ),
        migrations.AddField(
            model_name="exceptionrequest",
            name="risk_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="risk_owned_exceptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="exception_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="exceptions.exceptionrequest",
            ),
        ),
        migrations.AddIndex(
            model_name="reminderlog",
            index=models.Index(
                fields=["exception_request", "sent_at"],
                name="exceptions__excepti_7e5c46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exceptionrequest",
            index=models.Index(fields=["status"], name="exceptions__status_13ab50_idx"),
        ),
        migrations.AddIndex(
            model_name="exceptionrequest",
            index=models.Index(
                fields=["approval_deadline"], name="exceptions__approva_e8d020_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exceptionrequest",
            index=models.Index(
                fields=["exception_end_date"], name="exceptions__excepti_936c9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exceptionrequest",
            index=models.Index(
                fields=["requested_by", "status"], name="exceptions__request_92a0a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exceptionrequest",
            index=models.Index(
                fields=["assigned_approver", "status"],
                name="exceptions__assigne_e19136_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exceptionrequest",
            index=models.Index(
                fields=["created_at", "status"], name="exceptions__created_3dc6e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["exception_request", "timestamp"],
                name="exceptions__excepti_086844_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["timestamp"], name="exceptions__timesta_3fca98_idx"
            ),
        ),
    ]
