# Generated by Django 4.2 on 2026-02-27 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exceptions', '0003_exceptionrequest_reminderlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.CharField(choices=[('exception_requested', 'Exception Requested'), ('bu_approval_notified', 'BU CIO Notified'), ('bu_approval_decision', 'BU CIO Decision Received'), ('risk_assessment_notified', 'Risk Owner Notified'), ('risk_assessment_complete', 'Risk Assessment Complete'), ('final_decision', 'Final Decision Made')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='exceptions__excepti_086844_idx',
        ),
        migrations.AlterField(
            model_name='exceptionrequest',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft - Not Yet Submitted'), ('Submitted', 'Submitted - Pending BU CIO Approval'), ('AwaitingRiskOwner', 'BU CIO Approved - Awaiting Risk Owner Assessment'), ('AwaitingFinalDecision', 'Risk Assessment Complete - Awaiting Final Decision'), ('Approved', 'Approved - Active Exception'), ('Rejected', 'Rejected - Awaiting Resubmission'), ('Expired', 'Expired - Approval Deadline Passed'), ('Closed', 'Closed - Exception No Longer Valid')], db_index=True, default='Draft', max_length=30),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['exception_request', '-timestamp'], name='exceptions__excepti_086844_idx'),
        ),
        migrations.AddField(
            model_name='exceptioncheckpoint',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checkpoints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exceptioncheckpoint',
            name='exception_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='exceptions.exceptionrequest'),
        ),
        migrations.AddConstraint(
            model_name='exceptioncheckpoint',
            constraint=models.UniqueConstraint(fields=('exception_request', 'checkpoint'), name='unique_exception_checkpoint'),
        ),
    ]
