# Generated by Django 4.2 on 2026-02-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceptions', '0004_exceptioncheckpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='new_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='previous_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
