# Generated by Django 4.2 on 2026-03-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceptions', '0005_alter_auditlog_new_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionrequest',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft - Not Yet Submitted'), ('Submitted', 'Submitted - Pending BU CIO Approval'), ('AwaitingRiskOwner', 'BU CIO Approved - Awaiting Risk Owner Assessment'), ('Approved', 'Approved - Active Exception'), ('Rejected', 'Rejected - Awaiting Resubmission'), ('Expired', 'Expired - Approval Deadline Passed'), ('Closed', 'Closed - Exception No Longer Valid')], db_index=True, default='Draft', max_length=30),
        ),
    ]
