# Generated by Django 4.2 on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceptions', '0006_alter_exceptionrequest_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='riskissue',
            table='risk_issue',
        ),
        migrations.AddConstraint(
            model_name='riskissue',
            constraint=models.CheckConstraint(
                check=models.Q(inherent_risk_score__gte=0),
                name='risk_issue_inherent_score_gte_0',
            ),
        ),
    ]
