# Generated by Django 4.2 on 2026-03-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceptions', '0008_schema_freeze_validations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceptionrequest',
            name='assigned_risk_owner',
        ),
        migrations.AlterField(
            model_name='exceptionrequest',
            name='number_of_assets',
            field=models.IntegerField(help_text='Number of assets affected (minimum 1)'),
        ),
        migrations.AlterField(
            model_name='exceptionrequest',
            name='risk_score',
            field=models.IntegerField(blank=True, help_text='Calculated risk score (0+)', null=True),
        ),
    ]
