# Generated by Django 4.2 on 2026-03-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exceptions', '0009_rename_exceptions__excepti_086844_idx_auditlog_exc_ts_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='exceptions__excepti_086844_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='auditlog_exc_ts_idx',
            old_name='auditlog_exception_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='exceptionrequest',
            new_name='exc_reminder_deadln_idx',
            old_name='exception_reminder_deadline_idx',
        ),
    ]
