# Generated by Django 4.2 on 2026-04-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceptions', '0013_notificationdismissal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderlog',
            name='delivery_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='sent', max_length=20),
        ),
    ]
