# Generated by Django 4.2 on 2026-04-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exceptions", "0014_rename_expired_to_approval_deadline_passed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("SUBMIT", "Submitted for Approval"),
                    ("APPROVE", "Approved"),
                    ("REJECT", "Rejected"),
                    ("CLOSE", "Closed"),
                    ("EXPIRE", "Expired"),
                    ("MODIFY", "Superseded by Modification"),
                    ("EXTEND", "Superseded by Extension"),
                    ("REMIND", "Reminder Sent"),
                    ("ESCALATE", "Escalated"),
                    ("UPDATE", "Updated"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="exceptionrequest",
            name="approval_deadline",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="exceptionrequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exceptionrequest",
            name="exception_end_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="exceptionrequest",
            name="last_reminder_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exceptionrequest",
            name="reminder_stage",
            field=models.CharField(
                choices=[
                    ("None", "No reminder sent"),
                    ("Reminder_50", "50% of approval window"),
                    ("Reminder_75", "75% of approval window"),
                    ("Reminder_90", "90% of approval window"),
                    ("Expired_Notice", "Expired notification sent"),
                ],
                default="None",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="exceptionrequest",
            name="risk_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Low", "Low Risk"),
                    ("Medium", "Medium Risk"),
                    ("High", "High Risk"),
                    ("Critical", "Critical Risk"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exceptionrequest",
            name="risk_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exceptionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft - Not Yet Submitted"),
                    ("Submitted", "Submitted - Pending BU CIO Approval"),
                    (
                        "AwaitingRiskOwner",
                        "BU CIO Approved - Awaiting Risk Owner Assessment",
                    ),
                    ("Approved", "Approved - Active Exception"),
                    ("Rejected", "Rejected - Pending Decision"),
                    (
                        "ApprovalDeadlinePassed",
                        "Approval Deadline Passed Without Decision",
                    ),
                    ("Expired", "Expired - Exception End Date Passed"),
                    ("Modified", "Modified - Superseded by Approved Modification"),
                    ("Extended", "Extended - Superseded by Approved Extension"),
                    ("Closed", "Closed - Exception No Longer Valid"),
                ],
                db_index=True,
                default="Draft",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="reminderlog",
            name="channel",
            field=models.CharField(
                choices=[("email", "Email"), ("system", "System Log")],
                default="email",
                max_length=20,
            ),
        ),
    ]
