--
-- PostgreSQL database dump
--

\restrict XlP9zEk2yVsjJQI9t548RO4esyAJNvGjPSJbhQ1TzbtJE1VXiG2CFnhLJhgLJuq

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: grc_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO grc_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO grc_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO grc_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO grc_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO grc_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO grc_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO grc_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO grc_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO grc_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO grc_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO grc_user;

--
-- Name: exceptions_assetpurpose; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.exceptions_assetpurpose (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    weight integer NOT NULL
);


ALTER TABLE public.exceptions_assetpurpose OWNER TO grc_user;

--
-- Name: exceptions_assetpurpose_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.exceptions_assetpurpose ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exceptions_assetpurpose_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exceptions_assettype; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.exceptions_assettype (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    weight integer NOT NULL
);


ALTER TABLE public.exceptions_assettype OWNER TO grc_user;

--
-- Name: exceptions_assettype_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.exceptions_assettype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exceptions_assettype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exceptions_auditlog; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.exceptions_auditlog (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    performed_by_id integer,
    action_type character varying(50) NOT NULL,
    new_status character varying(30),
    previous_status character varying(30),
    details jsonb NOT NULL,
    exception_request_id bigint
);


ALTER TABLE public.exceptions_auditlog OWNER TO grc_user;

--
-- Name: exceptions_auditlog_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.exceptions_auditlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exceptions_auditlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exceptions_businessunit; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.exceptions_businessunit (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    bu_code character varying(50) NOT NULL,
    cio_id integer
);


ALTER TABLE public.exceptions_businessunit OWNER TO grc_user;

--
-- Name: exceptions_businessunit_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.exceptions_businessunit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exceptions_businessunit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exceptions_dataclassification; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.exceptions_dataclassification (
    id bigint NOT NULL,
    level character varying(100) NOT NULL,
    weight integer NOT NULL
);


ALTER TABLE public.exceptions_dataclassification OWNER TO grc_user;

--
-- Name: exceptions_dataclassification_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.exceptions_dataclassification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exceptions_dataclassification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exceptions_datacomponent; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.exceptions_datacomponent (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    weight integer NOT NULL
);


ALTER TABLE public.exceptions_datacomponent OWNER TO grc_user;

--
-- Name: exceptions_datacomponent_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.exceptions_datacomponent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exceptions_datacomponent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exceptions_exceptioncheckpoint; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.exceptions_exceptioncheckpoint (
    id bigint NOT NULL,
    checkpoint character varying(40) NOT NULL,
    status character varying(20) NOT NULL,
    completed_at timestamp with time zone,
    notes text NOT NULL,
    completed_by_id integer,
    exception_request_id bigint NOT NULL
);


ALTER TABLE public.exceptions_exceptioncheckpoint OWNER TO grc_user;

--
-- Name: exceptions_exceptioncheckpoint_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.exceptions_exceptioncheckpoint ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exceptions_exceptioncheckpoint_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exceptions_exceptionrequest; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.exceptions_exceptionrequest (
    id bigint NOT NULL,
    number_of_assets integer NOT NULL,
    short_description text NOT NULL,
    reason_for_exception text NOT NULL,
    compensatory_controls text NOT NULL,
    risk_score integer,
    risk_rating character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    approval_deadline timestamp with time zone,
    approved_at timestamp with time zone,
    exception_end_date timestamp with time zone,
    last_reminder_sent timestamp with time zone,
    reminder_stage character varying(50) NOT NULL,
    status character varying(30) NOT NULL,
    version integer NOT NULL,
    asset_purpose_id bigint NOT NULL,
    asset_type_id bigint NOT NULL,
    assigned_approver_id integer NOT NULL,
    assigned_risk_owner_id integer,
    business_unit_id bigint NOT NULL,
    data_classification_id bigint NOT NULL,
    exception_type_id bigint NOT NULL,
    internet_exposure_id bigint NOT NULL,
    requested_by_id integer NOT NULL,
    risk_issue_id bigint NOT NULL,
    risk_owner_id integer NOT NULL
);


ALTER TABLE public.exceptions_exceptionrequest OWNER TO grc_user;

--
-- Name: exceptions_exceptionrequest_data_components; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.exceptions_exceptionrequest_data_components (
    id bigint NOT NULL,
    exceptionrequest_id bigint CONSTRAINT exceptions_exceptionrequest_data_c_exceptionrequest_id_not_null NOT NULL,
    datacomponent_id bigint CONSTRAINT exceptions_exceptionrequest_data_comp_datacomponent_id_not_null NOT NULL
);


ALTER TABLE public.exceptions_exceptionrequest_data_components OWNER TO grc_user;

--
-- Name: exceptions_exceptionrequest_data_components_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.exceptions_exceptionrequest_data_components ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exceptions_exceptionrequest_data_components_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exceptions_exceptionrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.exceptions_exceptionrequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exceptions_exceptionrequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exceptions_exceptiontype; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.exceptions_exceptiontype (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    approval_sla_days integer NOT NULL
);


ALTER TABLE public.exceptions_exceptiontype OWNER TO grc_user;

--
-- Name: exceptions_exceptiontype_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.exceptions_exceptiontype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exceptions_exceptiontype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exceptions_internetexposure; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.exceptions_internetexposure (
    id bigint NOT NULL,
    label character varying(100) NOT NULL,
    weight integer NOT NULL
);


ALTER TABLE public.exceptions_internetexposure OWNER TO grc_user;

--
-- Name: exceptions_internetexposure_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.exceptions_internetexposure ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exceptions_internetexposure_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exceptions_reminderlog; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.exceptions_reminderlog (
    id bigint NOT NULL,
    channel character varying(20) NOT NULL,
    reminder_type character varying(50) NOT NULL,
    sent_at timestamp with time zone NOT NULL,
    delivery_status character varying(20) NOT NULL,
    message_content text NOT NULL,
    error_message text NOT NULL,
    exception_request_id bigint,
    sent_to_id integer
);


ALTER TABLE public.exceptions_reminderlog OWNER TO grc_user;

--
-- Name: exceptions_reminderlog_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.exceptions_reminderlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exceptions_reminderlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exceptions_riskissue; Type: TABLE; Schema: public; Owner: grc_user
--

CREATE TABLE public.exceptions_riskissue (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    inherent_risk_score integer NOT NULL
);


ALTER TABLE public.exceptions_riskissue OWNER TO grc_user;

--
-- Name: exceptions_riskissue_id_seq; Type: SEQUENCE; Schema: public; Owner: grc_user
--

ALTER TABLE public.exceptions_riskissue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exceptions_riskissue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: exceptions_assetpurpose exceptions_assetpurpose_name_9ec856d6_uniq; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_assetpurpose
    ADD CONSTRAINT exceptions_assetpurpose_name_9ec856d6_uniq UNIQUE (name);


--
-- Name: exceptions_assetpurpose exceptions_assetpurpose_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_assetpurpose
    ADD CONSTRAINT exceptions_assetpurpose_pkey PRIMARY KEY (id);


--
-- Name: exceptions_assettype exceptions_assettype_name_dc08403e_uniq; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_assettype
    ADD CONSTRAINT exceptions_assettype_name_dc08403e_uniq UNIQUE (name);


--
-- Name: exceptions_assettype exceptions_assettype_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_assettype
    ADD CONSTRAINT exceptions_assettype_pkey PRIMARY KEY (id);


--
-- Name: exceptions_auditlog exceptions_auditlog_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_auditlog
    ADD CONSTRAINT exceptions_auditlog_pkey PRIMARY KEY (id);


--
-- Name: exceptions_businessunit exceptions_businessunit_bu_code_key; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_businessunit
    ADD CONSTRAINT exceptions_businessunit_bu_code_key UNIQUE (bu_code);


--
-- Name: exceptions_businessunit exceptions_businessunit_name_0b733c58_uniq; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_businessunit
    ADD CONSTRAINT exceptions_businessunit_name_0b733c58_uniq UNIQUE (name);


--
-- Name: exceptions_businessunit exceptions_businessunit_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_businessunit
    ADD CONSTRAINT exceptions_businessunit_pkey PRIMARY KEY (id);


--
-- Name: exceptions_dataclassification exceptions_dataclassification_level_8c4f9322_uniq; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_dataclassification
    ADD CONSTRAINT exceptions_dataclassification_level_8c4f9322_uniq UNIQUE (level);


--
-- Name: exceptions_dataclassification exceptions_dataclassification_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_dataclassification
    ADD CONSTRAINT exceptions_dataclassification_pkey PRIMARY KEY (id);


--
-- Name: exceptions_datacomponent exceptions_datacomponent_name_9b2c063f_uniq; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_datacomponent
    ADD CONSTRAINT exceptions_datacomponent_name_9b2c063f_uniq UNIQUE (name);


--
-- Name: exceptions_datacomponent exceptions_datacomponent_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_datacomponent
    ADD CONSTRAINT exceptions_datacomponent_pkey PRIMARY KEY (id);


--
-- Name: exceptions_exceptioncheckpoint exceptions_exceptioncheckpoint_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptioncheckpoint
    ADD CONSTRAINT exceptions_exceptioncheckpoint_pkey PRIMARY KEY (id);


--
-- Name: exceptions_exceptionrequest_data_components exceptions_exceptionrequ_exceptionrequest_id_data_f562be13_uniq; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptionrequest_data_components
    ADD CONSTRAINT exceptions_exceptionrequ_exceptionrequest_id_data_f562be13_uniq UNIQUE (exceptionrequest_id, datacomponent_id);


--
-- Name: exceptions_exceptionrequest_data_components exceptions_exceptionrequest_data_components_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptionrequest_data_components
    ADD CONSTRAINT exceptions_exceptionrequest_data_components_pkey PRIMARY KEY (id);


--
-- Name: exceptions_exceptionrequest exceptions_exceptionrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptionrequest
    ADD CONSTRAINT exceptions_exceptionrequest_pkey PRIMARY KEY (id);


--
-- Name: exceptions_exceptiontype exceptions_exceptiontype_name_a6f76617_uniq; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptiontype
    ADD CONSTRAINT exceptions_exceptiontype_name_a6f76617_uniq UNIQUE (name);


--
-- Name: exceptions_exceptiontype exceptions_exceptiontype_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptiontype
    ADD CONSTRAINT exceptions_exceptiontype_pkey PRIMARY KEY (id);


--
-- Name: exceptions_internetexposure exceptions_internetexposure_label_2b4dc984_uniq; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_internetexposure
    ADD CONSTRAINT exceptions_internetexposure_label_2b4dc984_uniq UNIQUE (label);


--
-- Name: exceptions_internetexposure exceptions_internetexposure_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_internetexposure
    ADD CONSTRAINT exceptions_internetexposure_pkey PRIMARY KEY (id);


--
-- Name: exceptions_reminderlog exceptions_reminderlog_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_reminderlog
    ADD CONSTRAINT exceptions_reminderlog_pkey PRIMARY KEY (id);


--
-- Name: exceptions_riskissue exceptions_riskissue_pkey; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_riskissue
    ADD CONSTRAINT exceptions_riskissue_pkey PRIMARY KEY (id);


--
-- Name: exceptions_riskissue exceptions_riskissue_title_8ee96d2a_uniq; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_riskissue
    ADD CONSTRAINT exceptions_riskissue_title_8ee96d2a_uniq UNIQUE (title);


--
-- Name: exceptions_exceptioncheckpoint unique_exception_checkpoint; Type: CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptioncheckpoint
    ADD CONSTRAINT unique_exception_checkpoint UNIQUE (exception_request_id, checkpoint);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: exceptions__approva_e8d020_idx; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions__approva_e8d020_idx ON public.exceptions_exceptionrequest USING btree (approval_deadline);


--
-- Name: exceptions__assigne_e19136_idx; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions__assigne_e19136_idx ON public.exceptions_exceptionrequest USING btree (assigned_approver_id, status);


--
-- Name: exceptions__created_3dc6e5_idx; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions__created_3dc6e5_idx ON public.exceptions_exceptionrequest USING btree (created_at, status);


--
-- Name: exceptions__excepti_086844_idx; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions__excepti_086844_idx ON public.exceptions_auditlog USING btree (exception_request_id, "timestamp" DESC);


--
-- Name: exceptions__excepti_7e5c46_idx; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions__excepti_7e5c46_idx ON public.exceptions_reminderlog USING btree (exception_request_id, sent_at);


--
-- Name: exceptions__excepti_936c9e_idx; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions__excepti_936c9e_idx ON public.exceptions_exceptionrequest USING btree (exception_end_date);


--
-- Name: exceptions__request_92a0a3_idx; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions__request_92a0a3_idx ON public.exceptions_exceptionrequest USING btree (requested_by_id, status);


--
-- Name: exceptions__status_13ab50_idx; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions__status_13ab50_idx ON public.exceptions_exceptionrequest USING btree (status);


--
-- Name: exceptions__timesta_3fca98_idx; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions__timesta_3fca98_idx ON public.exceptions_auditlog USING btree ("timestamp");


--
-- Name: exceptions_assetpurpose_name_9ec856d6_like; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_assetpurpose_name_9ec856d6_like ON public.exceptions_assetpurpose USING btree (name varchar_pattern_ops);


--
-- Name: exceptions_assettype_name_dc08403e_like; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_assettype_name_dc08403e_like ON public.exceptions_assettype USING btree (name varchar_pattern_ops);


--
-- Name: exceptions_auditlog_exception_request_id_f4a8a59d; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_auditlog_exception_request_id_f4a8a59d ON public.exceptions_auditlog USING btree (exception_request_id);


--
-- Name: exceptions_auditlog_performed_by_id_bf233495; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_auditlog_performed_by_id_bf233495 ON public.exceptions_auditlog USING btree (performed_by_id);


--
-- Name: exceptions_auditlog_timestamp_a9f303dc; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_auditlog_timestamp_a9f303dc ON public.exceptions_auditlog USING btree ("timestamp");


--
-- Name: exceptions_businessunit_bu_code_25ffa072_like; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_businessunit_bu_code_25ffa072_like ON public.exceptions_businessunit USING btree (bu_code varchar_pattern_ops);


--
-- Name: exceptions_businessunit_cio_id_7d831f11; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_businessunit_cio_id_7d831f11 ON public.exceptions_businessunit USING btree (cio_id);


--
-- Name: exceptions_businessunit_name_0b733c58_like; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_businessunit_name_0b733c58_like ON public.exceptions_businessunit USING btree (name varchar_pattern_ops);


--
-- Name: exceptions_dataclassification_level_8c4f9322_like; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_dataclassification_level_8c4f9322_like ON public.exceptions_dataclassification USING btree (level varchar_pattern_ops);


--
-- Name: exceptions_datacomponent_name_9b2c063f_like; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_datacomponent_name_9b2c063f_like ON public.exceptions_datacomponent USING btree (name varchar_pattern_ops);


--
-- Name: exceptions_exceptioncheckpoint_completed_at_62e88a3b; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptioncheckpoint_completed_at_62e88a3b ON public.exceptions_exceptioncheckpoint USING btree (completed_at);


--
-- Name: exceptions_exceptioncheckpoint_completed_by_id_85c4200a; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptioncheckpoint_completed_by_id_85c4200a ON public.exceptions_exceptioncheckpoint USING btree (completed_by_id);


--
-- Name: exceptions_exceptioncheckpoint_exception_request_id_770ec04b; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptioncheckpoint_exception_request_id_770ec04b ON public.exceptions_exceptioncheckpoint USING btree (exception_request_id);


--
-- Name: exceptions_exceptionreques_datacomponent_id_d268447f; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptionreques_datacomponent_id_d268447f ON public.exceptions_exceptionrequest_data_components USING btree (datacomponent_id);


--
-- Name: exceptions_exceptionreques_exceptionrequest_id_ed5a0eee; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptionreques_exceptionrequest_id_ed5a0eee ON public.exceptions_exceptionrequest_data_components USING btree (exceptionrequest_id);


--
-- Name: exceptions_exceptionrequest_approval_deadline_dce70262; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptionrequest_approval_deadline_dce70262 ON public.exceptions_exceptionrequest USING btree (approval_deadline);


--
-- Name: exceptions_exceptionrequest_asset_purpose_id_4b3941bc; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptionrequest_asset_purpose_id_4b3941bc ON public.exceptions_exceptionrequest USING btree (asset_purpose_id);


--
-- Name: exceptions_exceptionrequest_asset_type_id_39130b2c; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptionrequest_asset_type_id_39130b2c ON public.exceptions_exceptionrequest USING btree (asset_type_id);


--
-- Name: exceptions_exceptionrequest_assigned_approver_id_81a2f70a; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptionrequest_assigned_approver_id_81a2f70a ON public.exceptions_exceptionrequest USING btree (assigned_approver_id);


--
-- Name: exceptions_exceptionrequest_assigned_risk_owner_id_70718389; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptionrequest_assigned_risk_owner_id_70718389 ON public.exceptions_exceptionrequest USING btree (assigned_risk_owner_id);


--
-- Name: exceptions_exceptionrequest_business_unit_id_bb6b030a; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptionrequest_business_unit_id_bb6b030a ON public.exceptions_exceptionrequest USING btree (business_unit_id);


--
-- Name: exceptions_exceptionrequest_created_at_455d1890; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptionrequest_created_at_455d1890 ON public.exceptions_exceptionrequest USING btree (created_at);


--
-- Name: exceptions_exceptionrequest_data_classification_id_7c81a8b1; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptionrequest_data_classification_id_7c81a8b1 ON public.exceptions_exceptionrequest USING btree (data_classification_id);


--
-- Name: exceptions_exceptionrequest_exception_end_date_2e0c1763; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptionrequest_exception_end_date_2e0c1763 ON public.exceptions_exceptionrequest USING btree (exception_end_date);


--
-- Name: exceptions_exceptionrequest_exception_type_id_1618bea2; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptionrequest_exception_type_id_1618bea2 ON public.exceptions_exceptionrequest USING btree (exception_type_id);


--
-- Name: exceptions_exceptionrequest_internet_exposure_id_9e56e34f; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptionrequest_internet_exposure_id_9e56e34f ON public.exceptions_exceptionrequest USING btree (internet_exposure_id);


--
-- Name: exceptions_exceptionrequest_requested_by_id_6d11ed72; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptionrequest_requested_by_id_6d11ed72 ON public.exceptions_exceptionrequest USING btree (requested_by_id);


--
-- Name: exceptions_exceptionrequest_risk_issue_id_d7d471d1; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptionrequest_risk_issue_id_d7d471d1 ON public.exceptions_exceptionrequest USING btree (risk_issue_id);


--
-- Name: exceptions_exceptionrequest_risk_owner_id_c883ad85; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptionrequest_risk_owner_id_c883ad85 ON public.exceptions_exceptionrequest USING btree (risk_owner_id);


--
-- Name: exceptions_exceptionrequest_status_84faff40; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptionrequest_status_84faff40 ON public.exceptions_exceptionrequest USING btree (status);


--
-- Name: exceptions_exceptionrequest_status_84faff40_like; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptionrequest_status_84faff40_like ON public.exceptions_exceptionrequest USING btree (status varchar_pattern_ops);


--
-- Name: exceptions_exceptiontype_name_a6f76617_like; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_exceptiontype_name_a6f76617_like ON public.exceptions_exceptiontype USING btree (name varchar_pattern_ops);


--
-- Name: exceptions_internetexposure_label_2b4dc984_like; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_internetexposure_label_2b4dc984_like ON public.exceptions_internetexposure USING btree (label varchar_pattern_ops);


--
-- Name: exceptions_reminderlog_exception_request_id_163337e6; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_reminderlog_exception_request_id_163337e6 ON public.exceptions_reminderlog USING btree (exception_request_id);


--
-- Name: exceptions_reminderlog_sent_at_82da6ea7; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_reminderlog_sent_at_82da6ea7 ON public.exceptions_reminderlog USING btree (sent_at);


--
-- Name: exceptions_reminderlog_sent_to_id_16e0d012; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_reminderlog_sent_to_id_16e0d012 ON public.exceptions_reminderlog USING btree (sent_to_id);


--
-- Name: exceptions_riskissue_title_8ee96d2a_like; Type: INDEX; Schema: public; Owner: grc_user
--

CREATE INDEX exceptions_riskissue_title_8ee96d2a_like ON public.exceptions_riskissue USING btree (title varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_auditlog exceptions_auditlog_exception_request_id_f4a8a59d_fk_exception; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_auditlog
    ADD CONSTRAINT exceptions_auditlog_exception_request_id_f4a8a59d_fk_exception FOREIGN KEY (exception_request_id) REFERENCES public.exceptions_exceptionrequest(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_auditlog exceptions_auditlog_performed_by_id_bf233495_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_auditlog
    ADD CONSTRAINT exceptions_auditlog_performed_by_id_bf233495_fk_auth_user_id FOREIGN KEY (performed_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_businessunit exceptions_businessunit_cio_id_7d831f11_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_businessunit
    ADD CONSTRAINT exceptions_businessunit_cio_id_7d831f11_fk_auth_user_id FOREIGN KEY (cio_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_exceptionrequest exceptions_exception_asset_purpose_id_4b3941bc_fk_exception; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptionrequest
    ADD CONSTRAINT exceptions_exception_asset_purpose_id_4b3941bc_fk_exception FOREIGN KEY (asset_purpose_id) REFERENCES public.exceptions_assetpurpose(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_exceptionrequest exceptions_exception_asset_type_id_39130b2c_fk_exception; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptionrequest
    ADD CONSTRAINT exceptions_exception_asset_type_id_39130b2c_fk_exception FOREIGN KEY (asset_type_id) REFERENCES public.exceptions_assettype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_exceptionrequest exceptions_exception_assigned_approver_id_81a2f70a_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptionrequest
    ADD CONSTRAINT exceptions_exception_assigned_approver_id_81a2f70a_fk_auth_user FOREIGN KEY (assigned_approver_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_exceptionrequest exceptions_exception_assigned_risk_owner__70718389_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptionrequest
    ADD CONSTRAINT exceptions_exception_assigned_risk_owner__70718389_fk_auth_user FOREIGN KEY (assigned_risk_owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_exceptionrequest exceptions_exception_business_unit_id_bb6b030a_fk_exception; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptionrequest
    ADD CONSTRAINT exceptions_exception_business_unit_id_bb6b030a_fk_exception FOREIGN KEY (business_unit_id) REFERENCES public.exceptions_businessunit(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_exceptioncheckpoint exceptions_exception_completed_by_id_85c4200a_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptioncheckpoint
    ADD CONSTRAINT exceptions_exception_completed_by_id_85c4200a_fk_auth_user FOREIGN KEY (completed_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_exceptionrequest exceptions_exception_data_classification__7c81a8b1_fk_exception; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptionrequest
    ADD CONSTRAINT exceptions_exception_data_classification__7c81a8b1_fk_exception FOREIGN KEY (data_classification_id) REFERENCES public.exceptions_dataclassification(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_exceptionrequest_data_components exceptions_exception_datacomponent_id_d268447f_fk_exception; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptionrequest_data_components
    ADD CONSTRAINT exceptions_exception_datacomponent_id_d268447f_fk_exception FOREIGN KEY (datacomponent_id) REFERENCES public.exceptions_datacomponent(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_exceptioncheckpoint exceptions_exception_exception_request_id_770ec04b_fk_exception; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptioncheckpoint
    ADD CONSTRAINT exceptions_exception_exception_request_id_770ec04b_fk_exception FOREIGN KEY (exception_request_id) REFERENCES public.exceptions_exceptionrequest(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_exceptionrequest exceptions_exception_exception_type_id_1618bea2_fk_exception; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptionrequest
    ADD CONSTRAINT exceptions_exception_exception_type_id_1618bea2_fk_exception FOREIGN KEY (exception_type_id) REFERENCES public.exceptions_exceptiontype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_exceptionrequest_data_components exceptions_exception_exceptionrequest_id_ed5a0eee_fk_exception; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptionrequest_data_components
    ADD CONSTRAINT exceptions_exception_exceptionrequest_id_ed5a0eee_fk_exception FOREIGN KEY (exceptionrequest_id) REFERENCES public.exceptions_exceptionrequest(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_exceptionrequest exceptions_exception_internet_exposure_id_9e56e34f_fk_exception; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptionrequest
    ADD CONSTRAINT exceptions_exception_internet_exposure_id_9e56e34f_fk_exception FOREIGN KEY (internet_exposure_id) REFERENCES public.exceptions_internetexposure(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_exceptionrequest exceptions_exception_requested_by_id_6d11ed72_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptionrequest
    ADD CONSTRAINT exceptions_exception_requested_by_id_6d11ed72_fk_auth_user FOREIGN KEY (requested_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_exceptionrequest exceptions_exception_risk_issue_id_d7d471d1_fk_exception; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptionrequest
    ADD CONSTRAINT exceptions_exception_risk_issue_id_d7d471d1_fk_exception FOREIGN KEY (risk_issue_id) REFERENCES public.exceptions_riskissue(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_exceptionrequest exceptions_exception_risk_owner_id_c883ad85_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_exceptionrequest
    ADD CONSTRAINT exceptions_exception_risk_owner_id_c883ad85_fk_auth_user FOREIGN KEY (risk_owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_reminderlog exceptions_reminderl_exception_request_id_163337e6_fk_exception; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_reminderlog
    ADD CONSTRAINT exceptions_reminderl_exception_request_id_163337e6_fk_exception FOREIGN KEY (exception_request_id) REFERENCES public.exceptions_exceptionrequest(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exceptions_reminderlog exceptions_reminderlog_sent_to_id_16e0d012_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: grc_user
--

ALTER TABLE ONLY public.exceptions_reminderlog
    ADD CONSTRAINT exceptions_reminderlog_sent_to_id_16e0d012_fk_auth_user_id FOREIGN KEY (sent_to_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO grc_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO grc_user;


--
-- PostgreSQL database dump complete
--

\unrestrict XlP9zEk2yVsjJQI9t548RO4esyAJNvGjPSJbhQ1TzbtJE1VXiG2CFnhLJhgLJuq

